#!C:/Users/Bob/AppData/Local/Programs/Python/Python36/python
import json
import cgi
from utils import WorkflowUtils as utils

print("Content-type: application/json")
print()

params = cgi.FieldStorage()
workflowText = params.getvalue('workflow')
package = params.getvalue("package")
if workflowText is None:
    workflowText = """
   {
  "workflows": [
    {
      "id": 1,
      "metadata": {
        "longname": "Subworkflow"
      },
      "operations": [
        {
          "id": 0,
          "metadata": {
            "longname": "BinaryMathRaster",
            "label": "BinaryMathRaster",
            "url": "http://130.89.221.193:75/binarymathraster",
            "resource": "REST",
            "description": "Returns a raster generated by pixel-by-pixel addition of two source rasters.  Source rasters must have the same bounding box and resolution.",
            "inputparametercount": 3,
            "outputparametercount": 1,
            "position": [
              287,
              12
            ]
          },
          "inputs": [
            {
              "id": 0,
              "identifier": "CoverageA",
              "name": "CoverageA",
              "type": "coverage",
              "description": "First input coverage",
              "optional": false,
              "url": "http://130.89.8.26:85/geoserver/ows?version=2.0.0&service=WCS&request=GetCoverage&coverageId=Statistics:sum_rainfall_average_20171010_2018420&format=image/geotiff",
              "value": "http://130.89.8.26:85/geoserver/ows?version=2.0.0&service=WCS&request=GetCoverage&coverageId=Statistics:sum_rainfall_average_20171010_2018420&format=image/geotiff"
            },
            {
              "id": 1,
              "identifier": "CoverageB",
              "name": "CoverageB",
              "type": "coverage",
              "description": "Second input coverage",
              "optional": false,
              "url": "http://130.89.8.26:85/geoserver/ows?version=2.0.0&service=WCS&request=GetCoverage&coverageId=Statistics:sum_rainfall_average_20171010_2018520&format=image/geotiff",
              "value": "http://130.89.8.26:85/geoserver/ows?version=2.0.0&service=WCS&request=GetCoverage&coverageId=Statistics:sum_rainfall_average_20171010_2018520&format=image/geotiff"
            },
            {
              "id": 2,
              "identifier": "operator",
              "name": "operator",
              "type": "text",
              "description": "Operator to be applied to rasters",
              "optional": false,
              "url": "",
              "value": "minus"
            }
          ],
          "outputs": [
            {
              "id": 0,
              "identifier": "result",
              "name": "result",
              "value": "",
              "type": "coverage",
              "description": "result"
            }
          ]
        },
        {
          "id": 1,
          "metadata": {
            "longname": "mapcalc2",
            "label": "mapcalc",
            "url": "http://130.89.221.193:75/ilwisoperations",
            "resource": "ILWIS",
            "description": "MapCalc 2",
            "inputparametercount": 3,
            "outputparametercount": 1,
            "position": [
              607,
              16
            ]
          },
          "inputs": [
            {
              "id": 0,
              "identifier": "Expression",
              "name": "Expression",
              "type": "String",
              "description": "The expression is an abstract expression were the numbers indicate indexes in the parameter list",
              "optional": false,
              "url": "",
              "value": "@1+@2"
            },
            {
              "id": 1,
              "identifier": "raster or number",
              "name": "raster or number",
              "type": "coverage",
              "description": "Rasters with numerical domain",
              "optional": false,
              "url": "http://130.89.8.26:85/geoserver/ows?version=2.0.0&service=WCS&request=GetCoverage&coverageId=Statistics:sum_rainfall_average_20171010_2018420&format=image/geotiff",
              "value": "http://130.89.8.26:85/geoserver/ows?version=2.0.0&service=WCS&request=GetCoverage&coverageId=Statistics:sum_rainfall_average_20171010_2018420&format=image/geotiff"
            },
            {
              "id": 2,
              "identifier": "raster or number",
              "name": "raster or number",
              "type": "coverage",
              "description": "Rasters with numerical domain",
              "optional": false,
              "url": "http://130.89.8.26:85/geoserver/ows?version=2.0.0&service=WCS&request=GetCoverage&coverageId=Statistics:sum_rainfall_average_20171010_2018520&format=image/geotiff",
              "value": "http://130.89.8.26:85/geoserver/ows?version=2.0.0&service=WCS&request=GetCoverage&coverageId=Statistics:sum_rainfall_average_20171010_2018520&format=image/geotiff"
            }
          ],
          "outputs": [
            {
              "id": 0,
              "identifier": "raster coverage",
              "name": "raster coverage",
              "description": "?",
              "value": "",
              "type": "coverage"
            }
          ]
        },
        {
          "id": 2,
          "metadata": {
            "longname": "BinaryMathRaster",
            "label": "BinaryMathRaster",
            "url": "http://130.89.221.193:75/binarymathraster",
            "resource": "REST",
            "description": "Returns a raster generated by pixel-by-pixel addition of two source rasters.  Source rasters must have the same bounding box and resolution.",
            "inputparametercount": 3,
            "outputparametercount": 1,
            "position": [
              464,
              232
            ]
          },
          "inputs": [
            {
              "id": 0,
              "identifier": "CoverageA",
              "name": "CoverageA",
              "type": "coverage",
              "description": "First input coverage",
              "optional": false,
              "url": "",
              "value": "0_to_0"
            },
            {
              "id": 1,
              "identifier": "CoverageB",
              "name": "CoverageB",
              "type": "coverage",
              "description": "Second input coverage",
              "optional": false,
              "url": "",
              "value": "1_to_0"
            },
            {
              "id": 2,
              "identifier": "operator",
              "name": "operator",
              "type": "text",
              "description": "Operator to be applied to rasters",
              "optional": false,
              "url": "",
              "value": "divide"
            }
          ],
          "outputs": [
            {
              "id": 0,
              "identifier": "result",
              "name": "result",
              "value": "",
              "type": "coverage",
              "description": "result"
            }
          ]
        }
      ],
      "connections": [
        {
          "fromOperationID": 0,
          "toOperationID": 2,
          "fromParameterID": 0,
          "toParameterID": 0
        },
        {
          "fromOperationID": 1,
          "toOperationID": 2,
          "fromParameterID": 0,
          "toParameterID": 1
        }
      ]
    }
  ]
}"""

workflowJSON = json.loads(workflowText)

if package is None:
    package = 'QGIS'
if package == "ILWIS":
    print(workflowText)
elif package == "QGIS":
    result = utils.piwToQgisWorkflow(workflowText)
    print(result)
else:
    print(workflowText)
